cameras: 5


camera: cam-glider-vista
  position: -15.0 14.73 23.0
  rotation: 2.77 242.61 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000

camera: cam-glider-tail
  position: 0 3 10
  rotation: 6.38 176 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


camera: maincam
  position: 76 2 -270
  rotation: 0 -90 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


camera: highcam
  position: 231 27 -497
  rotation: -38 37 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


camera: cornercam
  position: 76 200 -270
  rotation: -66 -81 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000




entities: 10

entity: glider-rig
  model: null
  position: 81.9 1.49 272.6
  rotation: 2 155 0
  scale: .05 .05 .05
  velocity: 0 0 0
  angleVelocity: 0 0 0

    entity: glider-model
      model: glider
      position: 0 0 0
      rotation: 0 90 0
      scale: 1 1 1
      velocity: 0 0 0
      angleVelocity: 0 0 0


    entity: glider-propeller-rig
      model: null
      position: 0 .7 .4
      rotation: 0 90 0
      scale: 1 1 1
      velocity: 0 0 0
      angleVelocity: 2160 0 0


          entity: glider-propeller
            model: propeller
            position: 0 0 0
            rotation: 0 0 0
            scale: 1 1 1
            velocity: 0 0 0
            angleVelocity: 0 0 0






entity: city
  model: rungholt
  position: 78 1.3 270
  rotation: 0 -30 0
  scale: 0.02 0.02 0.02
  velocity: 0 0 0
  angleVelocity: 0 0 0


entity: terrain
  model: terrain
  position: 0 0 0
  rotation: 0 0 0
  scale: 250 15 500
  velocity: 0 0 0
  angleVelocity: 0 0 0



entity: cloud1
  model: cloud
  position: -250 40 -500
  rotation: 0 0 0
  scale: 1000 15 2000
  velocity: 0 0 0
  angleVelocity: 0 0 0


entity: cloud2
  model: cloud
  position: -250 50 -500
  rotation: 0 0 0
  scale: 1000 15 2000
  velocity: 0 0 0
  angleVelocity: 0 0 0


entity: cloud3
  model: cloud
  position: -250 60 -500
  rotation: 0 0 0
  scale: 1000 15 2000
  velocity: 0 0 0
  angleVelocity: 0 0 0

entity: cloud4
  model: cloud
  position: -250 70 -500
  rotation: 0 0 0
  scale: 1000 15 2000
  velocity: 0 0 0
  angleVelocity: 0 0 0





pointlights: 0

hasSun: 1

dirlight: distantSunLight
  rotation: 0 45 0
  angleVelocity: 0 0 0
  intensities: 0.15 0.15 0.1


relations: 5

  glider-model: 0
  glider-cam: 0
  glider-propeller: 0

  glider-propeller-rig: 1
    glider-propeller

  glider-rig: 4
    cam-glider-vista
    cam-glider-tail
    glider-model
    glider-propeller-rig



  

