cameras: 2

camera: maincam
  position: 20 19 -49
  rotation: 0 -180 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


camera: glider-cam
  position: -1 2 3
  rotation: 0 180 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


entities: 6



entity: glider-rig
  model: null
  position: 20 3 50
  rotation: 0 0 0
  scale: .05 .05 .05
  velocity: 0 0 0
  angleVelocity: 0 0 0

    entity: glider-model
      model: glider
      position: 0 0 0
      rotation: 0 90 0
      scale: 1 1 1
      velocity: 0 0 0
      angleVelocity: 0 0 0


    entity: glider-propeller-rig
      model: null
      position: 0 .7 .4
      rotation: 0 90 0
      scale: 1 1 1
      velocity: 0 0 0
      angleVelocity: 2160 0 0


          entity: glider-propeller
            model: propeller
            position: 0 0 0
            rotation: 0 0 0
            scale: 1 1 1
            velocity: 0 0 0
            angleVelocity: 0 0 0



entity: terrain
  model: terrain
  position: 0 0 0
  rotation: 0 0 0
  scale: 250 15 500
  velocity: 0 0 0
  angleVelocity: 0 0 0


entity: cloud
  model: cloud
  position: -125 40 -250
  rotation: 0 0 0
  scale: 500 15 1000
  velocity: 0 0 0
  angleVelocity: 0 0 0



pointlights: 0

hasSun: 1

dirlight: distantSunLight
  rotation: 0 45 0
  angleVelocity: 0 0 0
  intensities: 0.15 0.15 0.1


relations: 5

  glider-model: 0
  glider-cam: 0
  glider-propeller: 0

  glider-propeller-rig: 1
    glider-propeller

  glider-rig: 3
    glider-model
    glider-cam
    glider-propeller-rig


  

