cameras: 1

camera: maincam
  position: 0 0 -20
  rotation: 0 0 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: orbital
  fov: 90
  nearClip: 0.1
  farClip: 4000

entities: 1

entity: glider
  model: glider
  position: 0 0 0
  rotation: 0 0 0
  scale: 5 5 5
  velocity: 0 0 0
  angleVelocity: 0 0 0

pointlights: 0

hasSun: 0


relations: 0
