cameras: 2

camera: maincam
  position: 20 3.5 -48
  rotation: 0 -180 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


camera: glider-cam
  position: 0 2 7
  rotation: 0 180 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 40000


entities: 3

entity: terrain
  model: terrain
  position: 0 0 0
  rotation: 0 0 0
  scale: 250 5 500
  velocity: 0 0 0
  angleVelocity: 0 0 0


  entity: glider-rig
    model: null
    position: 20 3 50
    rotation: 0 0 0
    scale: .05 .05 .05
    velocity: 0 0 0
    angleVelocity: 0 0 0

  entity: glider-model
    model: glider
    position: 0 0 0
    rotation: -90 0 90
    scale: 1 1 1
    velocity: 0 0 0
    angleVelocity: 0 0 0


pointlights: 0

hasSun: 1

dirlight: distantSunLight
  rotation: 0 45 0
  angleVelocity: 0 0 0
  intensities: 0.15 0.15 0.1


relations: 3

  glider-model: 0
  glider-cam: 0

  glider-rig: 2
    glider-model
    glider-cam


  

