cameras: 1

camera: maincam
  position: 0 10 0
  rotation: 0 -90 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 4000

entities: 1

entity: terrain
  model: terrain
  position: 0 0 0
  rotation: 0 0 0
  scale: 50 5 100
  velocity: 0 0 0
  angleVelocity: 0 0 0

pointlights: 0

hasSun: 1

dirlight: distantSunLight
  rotation: 0 45 0
  angleVelocity: 0 0 0
  intensities: 0.15 0.15 0.1


relations: 0
