cameras: 1

camera: maincam
  position: 20 3.5 -48
  rotation: 0 -180 0
  velocity: 0 0 0
  angleVelocity: 0 0 0
  mode: freelook
  fov: 90
  nearClip: 0.1
  farClip: 4000

entities: 2

entity: terrain
  model: terrain
  position: 0 0 0
  rotation: 0 0 0
  scale: 50 5 100
  velocity: 0 0 0
  angleVelocity: 0 0 0


  entity: glider
    model: glider
    position: 20 3 50
    rotation: -90 0 0
    scale: .05 .05 .05
    velocity: 0 0 0
    angleVelocity: 0 0 0



pointlights: 0

hasSun: 1

dirlight: distantSunLight
  rotation: 0 45 0
  angleVelocity: 0 0 0
  intensities: 0.15 0.15 0.1


relations: 0
